[package]
name = "gc"
version = "0.1.0"
authors = ["jeroen wijdemans <jeroen.wijdemans@gmail.com>"]

#[features]
#default = ["yaml"]

[dependencies]
clap = {version = "2.19", features = ["yaml"]}
csv = "1.0.0-beta.3"
serde = "1.0.11"
serde_derive = "1.0.11"
ansi_term = "0.9"